# Generated by Django 6.1 on 2026-09-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversation_last_updated_customer_last_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='knowledge_base/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('indexed', models.BooleanField(default=False)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
