# Generated by Django 6.1 on 2026-09-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('message_text', models.TextField()),
                ('response_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('blocked_hmac', 'Blocked - Invalid Signature'), ('blocked_rate', 'Blocked - Rate Limited'), ('blocked_injection', 'Blocked - Injection Attempt'), ('blocked_type', 'Blocked - Unsupported Type'), ('failed', 'Failed - Pipeline Error'), ('fallback', 'Fallback - Guardrail Failed')], max_length=30)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
